services:
  backend:
    build: ./backend
    volumes:
      - ./db:/app/db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MOCK_BACKEND: ${MOCK_BACKEND}
    ports:
      - "8000:8000"
    depends_on: []
    networks:
      - nivii-net

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend
    networks:
      - nivii-net
networks:
  nivii-net:
    driver: bridge
